services:
  - type: web
    name: whatsapp-bot-v3
    env: node
    plan: free
    runtime: node
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
      - key: RENDER_EXTERNAL_URL
        value: https://wa-bot-v3.onrender.com
      # Enhanced keep-alive configuration
      - key: KEEP_ALIVE_AGGRESSIVE
        value: true
      - key: KEEP_ALIVE_INTERVAL
        value: 120000
    autoDeploy: true
    healthCheckPath: /health
    # Enhanced resource allocation for better stability
    disk: 512MB
    # Restart policy for better reliability
    restartPolicy: always
