#!/bin/bash
# Quick Setup Guide for External Monitoring - Render Free Tier

clear
echo "════════════════════════════════════════════════════════════════"
echo "🚨 CRITICAL: Set Up External Monitoring for Render Free Tier"
echo "════════════════════════════════════════════════════════════════"
echo ""
echo "⚠️  YOUR BOT WENT OFFLINE TODAY BECAUSE:"
echo "   • Render free tier spins down after 15 min inactivity"
echo "   • 50+ second cold start disconnects WhatsApp"
echo "   • Internal keep-alive alone is NOT enough"
echo ""
echo "✅ SOLUTION: External monitoring (5 minutes setup)"
echo ""
echo "════════════════════════════════════════════════════════════════"
echo ""

# Your Render URL
RENDER_URL="https://wa-bot-v3.onrender.com"
HEALTH_URL="${RENDER_URL}/health"

echo "📋 Your Bot URLs:"
echo "   Dashboard: $RENDER_URL"
echo "   Health Check: $HEALTH_URL"
echo ""

echo "🔍 Testing health endpoint..."
HTTP_STATUS=$(curl -s -o /dev/null -w "%{http_code}" "$HEALTH_URL" 2>/dev/null || echo "000")

if [ "$HTTP_STATUS" = "200" ]; then
    echo "✅ Bot is currently ONLINE"
else
    echo "⚠️  Bot is currently OFFLINE or spinning up (Status: $HTTP_STATUS)"
    echo "   This is expected if service just spun down"
fi

echo ""
echo "════════════════════════════════════════════════════════════════"
echo "🥇 OPTION 1: UptimeRobot (RECOMMENDED - 100% Free)"
echo "════════════════════════════════════════════════════════════════"
echo ""
echo "⏱️  Setup Time: 3 minutes"
echo "✨ Features: 50 monitors, 5-min intervals, SMS alerts"
echo ""
echo "📝 STEP-BY-STEP:"
echo ""
echo "1. Open this URL in your browser:"
echo "   👉 https://uptimerobot.com/signUp"
echo ""
echo "2. Create FREE account:"
echo "   • Enter your email"
echo "   • Verify email"
echo "   • Login"
echo ""
echo "3. Create Monitor:"
echo "   • Click [+ Add New Monitor]"
echo "   • Monitor Type: HTTP(s)"
echo "   • Friendly Name: CloudNextra WhatsApp Bot"
echo "   • URL: $HEALTH_URL"
echo "   • Monitoring Interval: 5 minutes"
echo "   • Click [Create Monitor]"
echo ""
echo "4. Done! ✅"
echo "   • Bot will NEVER go offline again"
echo "   • You'll get email alerts if it does"
echo ""
echo "════════════════════════════════════════════════════════════════"
echo "🥈 OPTION 2: Cron-Job.org (Alternative)"
echo "════════════════════════════════════════════════════════════════"
echo ""
echo "⏱️  Setup Time: 3 minutes"
echo ""
echo "1. Open: https://cron-job.org/en/signup"
echo "2. Create account and verify email"
echo "3. Click [Create cronjob]"
echo "4. Title: CloudNextra Bot Monitor"
echo "5. URL: $HEALTH_URL"
echo "6. Schedule: */5 * * * * (every 5 minutes)"
echo "7. Click [Create cronjob]"
echo ""
echo "════════════════════════════════════════════════════════════════"
echo "📊 Expected Results AFTER Setup:"
echo "════════════════════════════════════════════════════════════════"
echo ""
echo "WITHOUT External Monitoring:"
echo "  ⏱️  Uptime: ~95-97%"
echo "  🔴 Risk: Bot can still go offline"
echo ""
echo "WITH External Monitoring (UptimeRobot):"
echo "  ⏱️  Uptime: 99.5-99.9% ✅"
echo "  🟢 Bot NEVER spins down"
echo "  🚀 Always responds instantly"
echo ""
echo "════════════════════════════════════════════════════════════════"
echo "🎯 ACTION REQUIRED:"
echo "════════════════════════════════════════════════════════════════"
echo ""
echo "1. Choose ONE option above (UptimeRobot recommended)"
echo "2. Set it up NOW (takes only 3 minutes)"
echo "3. Your bot will stay online 99.9% of the time"
echo ""
echo "⚠️  Without this, your bot WILL go offline every 15-20 minutes"
echo ""
echo "════════════════════════════════════════════════════════════════"
